apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - secret.yaml
  - another-secret.yaml

commonLabels:
  env: pigs

configMapGenerator:
  - name: hello-server-config-map
    files:
      - pigs.conf

patches:
  - target:
      kind: Deployment
      name: hello-server
    path: deployment.yaml
